wish=("hello ,")
print(wish)
name=(input("Enter the name :"))
print(name)
age=input("enter the age :")
print("My age is :",age)
DOB=input("Entet the DOB :")
print("My DOB is :",DOB)
location=input("Enter the location :")
print("My location is :",location)
c_name=input("Enter the collage name :")  
print("My collage name is :",c_name)
print(wish,"My name is",name,".I am",age,"years old.","My date of brith is",DOB,".My location is",location,".I completed my degree",c_name)
      